export const Users = [
  {
    id: 1,
    profilePicture: "/assets/post-img-1.jpg",
    username: "Faizan Azad",
  },
  {
    id: 2,
    profilePicture: "/assets/post-img-2.jpeg",
    username: "Zishan Azad",
  },
  {
    id: 3,
    profilePicture: "/assets/post-img-3.jpeg",
    username: "faiza Azad",
  },
  {
    id: 4,
    profilePicture: "/assets/post-img-4.jpeg",
    username: "Sana Azad",
  },
  {
    id: 5,
    profilePicture: "/assets/post-img-5.jpeg",
    username: "Kahkashan",
  },
  {
    id: 6,
    profilePicture: "/assets/post-img-6.jpeg",
    username: "Ahnaf Shahid",
  },
  {
    id: 7,
    profilePicture: "/assets/post-img-7.webp",
    username: "Muawiyah Shahid",
  },
  {
    id: 8,
    profilePicture: "/assets/WhatsApp Image 2022-06-23 at 5.27.32 PM (1).jpeg",
    username: "Muawiyah Shahid",
  },
  {
    id: 9,
    profilePicture: "/assets/post-img-9.jpg",
    username: "Muawiyah Shahid",
  },
  {
    id: 10,
    profilePicture: "/assets/post-img-10.jpg",
    username: "Muawiyah Shahid",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Liove For All, Hatred For None.",
    photo: "/assets/post-img-1.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "/assets/post-img-2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "/assets/post-img-3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "/assets/post-img-4.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "/assets/post-img-5.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "/assets/post-img-6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "/assets/post-img-7.webp",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "/assets/WhatsApp Image 2022-06-23 at 5.27.32 PM (1).jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "/assets/post-img-9.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "/assets/post-img-10.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
